export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
 <>
 {children}
 <div>
    <h1>
        Features Products
    </h1>
 </div>
 </>
  );
}
