export const metadata = {
    title: "Next.js",
    description: "Generated by Next.js",
  };
  
  export default function AuthLayout({ children }) {
    return (
   <>
   
   <div>
      <h1>
          Welcome to our Login & Register Form
      </h1>
   </div>
   {children}
   </>
    );
  }
  