import './styles/globals.css'
export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
     
      <body>
      {/* <header>
        <div>
          <h1 className="bg-red-500 py-4">Header</h1>
        </div>
      </header> */}
        {children}
        {/* <footer>
        <div>
          <h1 className="black text-white text-center py-4">Footer</h1>
        </div>
      </footer> */}
        </body>
  
    </html>
  )
}
